#!/bin/bash
# Refresh this repo's snapshot of the live deployment.
#
# Two things get captured:
#   1. the code (the deployment is the source of truth for what is running)
#   2. a CONSISTENT copy of the live SQLite database, via VACUUM INTO — copying the
#      .db with cp/rsync can miss committed transactions still sitting in the WAL
#
# and a human-readable docs/STATE.md, because a .db file does not diff in git.
#
# Resend only retains email for 30 days and this database is the only off-box
# archive of the CRM, so run this after any meaningful batch.
#
# Usage: ./scripts/snapshot-state.sh [--commit]

set -euo pipefail

LIVE_PAD="${LIVE_PAD:-/home/boxed/resend-pad}"
REPO="$(cd "$(dirname "$0")/.." && pwd)"

echo "repo:  $REPO"
echo "live:  $LIVE_PAD"

# --- code -------------------------------------------------------------------
rsync -a \
  --exclude='.env' --exclude='.env.bak*' --exclude='*.log' \
  --exclude='.gitignore' \
  --exclude='data/' --exclude='leads/data/' --exclude='leads/attic/' --exclude='attic/' \
  --exclude='node_modules/' --exclude='__pycache__/' \
  --exclude='*.bak-*' --exclude='*.pre-import' --exclude='*.pre-token-fix' \
  "$LIVE_PAD/" "$REPO/pad/"

# --- database ---------------------------------------------------------------
node "$LIVE_PAD/tools/db-snapshot.cjs" "$REPO/pad/data/outreach.db"

# --- readable state ---------------------------------------------------------
{
  echo "# Pipeline state"
  echo
  echo "Generated by \`scripts/snapshot-state.sh\` from the live database"
  echo "(\`OUTREACH_DB=$LIVE_PAD/data/outreach.db\`) so the state is readable in git"
  echo "history — \`pad/data/outreach.db\` itself is a binary that does not diff."
  echo
  echo '```'
  node "$LIVE_PAD/tools/db-report.cjs"
  echo '```'
} > "$REPO/docs/STATE.md"

cd "$REPO"
git add -A
git --no-pager diff --cached --stat

if [ "${1:-}" = "--commit" ]; then
  STAMP="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  LEADS="$(node -e "process.env.OUTREACH_DB='$REPO/pad/data/outreach.db';console.log(require('$REPO/pad/db.cjs').val('SELECT COUNT(*) FROM leads'))" 2>/dev/null || echo '?')"
  git commit -m "chore: refresh state snapshot ($STAMP, $LEADS leads)"
  echo "committed. push with: git push"
else
  echo "(dry run — re-run with --commit to commit)"
fi
